workflows:
  react-native-ios:
    name: React Native iOS Build (Native Xcode)
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_NAME: "lo-scanitem-app"
      node: 20.11.1
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install node modules and CocoaPods
        script: |
          npm ci
          cd ios
          pod install
      - name: Build .ipa with Xcode
        script: |
          xcodebuild \
            -workspace ios/loscanitemapp.xcworkspace \
            -scheme loscanitemapp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/loscanitemapp.xcarchive \
            clean archive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/build/loscanitemapp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios
    artifacts:
      - build/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - maggiorealica.kartiyanta@wingscorp.com
