workflows:
  build-ios-ipa:
    name: Build iOS IPA without App Store credentials
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_NAME: "lo-scanitem-app"
        BUNDLE_ID: "com.maggiore.loscanitemapp"
      node: 20.11.1
      xcode: latest
      cocoapods: default
      flutter: stable
      groups:
        - expo-token   # if you need EXPO_TOKEN to fetch private packages, otherwise remove
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm ci
      - name: Generate iOS native project
        script: |
          npx expo prebuild --platform ios
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: List available schemes
        script: |
          xcodebuild -workspace ios/loscanitemapp.xcworkspace -list
      - name: Build archive
        script: |
          xcodebuild -workspace ios/loscanitemapp.xcworkspace \
                    -scheme loscanitemapp \
                    -sdk iphoneos \
                    -configuration Release \
                    -allowProvisioningUpdates \
                    -archivePath $CM_BUILD_DIR/build/loscanitemapp.xcarchive \
                    clean archive
      - name: Export .ipa
        script: |
          # Use exportOptions.plist with method "development" or "ad-hoc"
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/$APP_NAME.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - maggiorealica.kartiyanta@wingscorp.com
